language: python
python:
  - "3.7"
before_install:
  - sudo apt-get install fortunes fortune-mod cowsay
# command to install dependencies
# nothing needed so far
install: "pip install -r requirements.txt"
# command to run tests
script: python -m unittest discover tests "*.py"
