language: python
python:
  - "3.4"
before_install:
  - sudo apt-get install cowsay
  - sudo apt-get install fortune-mod
# command to install dependencies
# nothing needed so far
install: "pip install -r requirements.txt"
# command to run tests
script: python -m unittest discover tests "*.py"
